[workspace]
members = ["programs/*"]

[programs.devnet]
max = "EfKNU2eApaQY53ghPR4t3wTuGYSrvSa26NJMo37e1UdM"
max-limit-orders = "YOUR_LIMIT_ORDERS_PROGRAM_ID"
max-dca = "YOUR_DCA_PROGRAM_ID"

[programs.mainnet]
max = "EfKNU2eApaQY53ghPR4t3wTuGYSrvSa26NJMo37e1UdM"
max-limit-orders = "YOUR_LIMIT_ORDERS_PROGRAM_ID"
max-dca = "YOUR_DCA_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "phantom-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[toolchain]
anchor_version = "0.29.0"
