name = "max"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "API_KEYS_KV"
id = "21e449919ee04486bd1b6456a6684ff0"
preview_id = "21e449919ee04486bd1b6456a6684ff0"

[[kv_namespaces]]
binding = "DEVELOPERS_KV"
id = "e6e221ee390d461bbe2dc737752da27f"
preview_id = "e6e221ee390d461bbe2dc737752da27f"

[[kv_namespaces]]
binding = "USAGE_KV"
id = "079a1cc4c4934884b25b9c8a3f3c674d"
preview_id = "079a1cc4c4934884b25b9c8a3f3c674d"

# External packages that should not be bundled
# For Production environment
[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.bundle]
external = [
  "@solana/web3.js",
  "@solana/spl-token",
  "buffer",
  "stream",
  "crypto",
  "http",
  "https",
  "url",
  "zlib",
  "ws",
  "node-fetch",
  "bignumber.js",
  "superstruct"
]

# KV namespaces must be repeated in production environment
[[env.production.kv_namespaces]]
binding = "API_KEYS_KV"
id = "21e449919ee04486bd1b6456a6684ff0"

[[env.production.kv_namespaces]]
binding = "DEVELOPERS_KV"
id = "e6e221ee390d461bbe2dc737752da27f"

[[env.production.kv_namespaces]]
binding = "USAGE_KV"
id = "079a1cc4c4934884b25b9c8a3f3c674d"

# For Preview environment
[env.preview]
compatibility_flags = ["nodejs_compat"]

[env.preview.bundle]
external = [
  "@solana/web3.js",
  "@solana/spl-token",
  "buffer",
  "stream",
  "crypto",
  "http",
  "https",
  "url",
  "zlib",
  "ws",
  "node-fetch",
  "bignumber.js",
  "superstruct"
]

[[env.preview.kv_namespaces]]
binding = "API_KEYS_KV"
id = "21e449919ee04486bd1b6456a6684ff0"
preview_id = "21e449919ee04486bd1b6456a6684ff0"

[[env.preview.kv_namespaces]]
binding = "DEVELOPERS_KV"
id = "e6e221ee390d461bbe2dc737752da27f"
preview_id = "e6e221ee390d461bbe2dc737752da27f"

[[env.preview.kv_namespaces]]
binding = "USAGE_KV"
id = "079a1cc4c4934884b25b9c8a3f3c674d"
preview_id = "079a1cc4c4934884b25b9c8a3f3c674d"
